version: '3'

services:
  frontend:
    build: .
    command: ["npm", "start"]
    volumes:
      - .:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: